export interface Procedure {
  slug: string
  name: string
  keywords: string[]
  seoIntro: string
  faq: { q: string; a: string }[]
}

export const PROCEDURES: Procedure[] = [
  { slug: 'botox', name: 'Botox', keywords: ['botox aftercare instructions', 'botox aftercare generator', 'botox post care template'], seoIntro: 'Generate clear, professional Botox aftercare instructions for your patients in seconds, branded with your clinic name and ready to hand out.', faq: [ { q: 'Why is Botox aftercare important?', a: 'Proper aftercare reduces the risk of bruising and product migration and helps results settle evenly over the first two weeks.' }, { q: 'What should patients avoid after Botox?', a: 'Lying down, vigorous exercise, alcohol, and rubbing the treated area for the first 24 hours.' }, { q: 'How long until Botox results show?', a: 'Initial effects appear in 3-5 days, with full results at around 14 days.' } ] },
  { slug: 'lip-filler', name: 'Lip Filler', keywords: ['lip filler aftercare instructions', 'lip filler aftercare generator', 'dermal filler post care'], seoIntro: 'Create branded lip filler aftercare sheets for your clients instantly — covering swelling, bruising, and what to avoid.', faq: [ { q: 'Is swelling normal after lip filler?', a: 'Yes — swelling peaks at 24-48 hours and usually settles within a week.' }, { q: 'What should clients avoid after lip filler?', a: 'Heat, strenuous exercise, alcohol, and pressure on the lips for 24-48 hours.' }, { q: 'When can clients wear lipstick again?', a: 'Generally after 24 hours, once injection points have closed.' } ] },
  { slug: 'microneedling', name: 'Microneedling', keywords: ['microneedling aftercare instructions', 'microneedling aftercare generator', 'microneedling post care'], seoIntro: 'Generate professional microneedling aftercare instructions with your clinic branding — redness timeline, sun care, and product guidance.', faq: [ { q: 'How long does redness last after microneedling?', a: 'Redness typically resembles a mild sunburn for 24-72 hours.' }, { q: 'When can clients wear makeup after microneedling?', a: 'Usually after 24 hours to let the skin barrier recover.' }, { q: 'Is sunscreen required after microneedling?', a: 'Yes — broad-spectrum SPF is essential as skin is more photosensitive.' } ] },
  { slug: 'chemical-peel', name: 'Chemical Peel', keywords: ['chemical peel aftercare instructions', 'chemical peel aftercare generator', 'chemical peel post care'], seoIntro: 'Create clear chemical peel aftercare instructions for clients — peeling expectations, moisturizing, and sun protection.', faq: [ { q: 'When will skin start peeling after a chemical peel?', a: 'Peeling usually begins on day 2-3 and lasts up to a week depending on depth.' }, { q: 'Should clients peel the skin manually?', a: 'No — let it shed naturally to avoid scarring or hyperpigmentation.' }, { q: 'What products should be avoided after a peel?', a: 'Retinoids, exfoliants, and active acids until the skin has fully recovered.' } ] },
  { slug: 'laser-hair-removal', name: 'Laser Hair Removal', keywords: ['laser hair removal aftercare instructions', 'laser hair removal aftercare generator', 'laser hair removal post care'], seoIntro: 'Generate branded laser hair removal aftercare sheets — cooling, sun avoidance, and shedding guidance for your clients.', faq: [ { q: 'Is redness normal after laser hair removal?', a: 'Mild redness and bumps around follicles are common for 24-48 hours.' }, { q: 'Can clients sunbathe after laser hair removal?', a: 'No — sun exposure should be avoided for at least two weeks.' }, { q: 'When does treated hair fall out?', a: 'Shedding typically occurs over 1-3 weeks after treatment.' } ] },
  { slug: 'dermaplaning', name: 'Dermaplaning', keywords: ['dermaplaning aftercare instructions', 'dermaplaning aftercare generator', 'dermaplaning post care'], seoIntro: 'Create dermaplaning aftercare instructions with your branding — sensitivity, sun care, and product timing.', faq: [ { q: 'Is skin sensitive after dermaplaning?', a: 'Yes — skin can feel tight and sensitive for 24-48 hours.' }, { q: 'When can clients use actives after dermaplaning?', a: 'Wait 24-72 hours before resuming retinoids or exfoliating acids.' }, { q: 'Does dermaplaning require sunscreen?', a: 'Yes — freshly exfoliated skin is more sensitive to UV.' } ] },
  { slug: 'hydrafacial', name: 'HydraFacial', keywords: ['hydrafacial aftercare instructions', 'hydrafacial aftercare generator', 'hydrafacial post care'], seoIntro: 'Generate HydraFacial aftercare instructions for clients with your clinic branding — hydration and product guidance.', faq: [ { q: 'Can clients wear makeup after a HydraFacial?', a: 'It is best to wait at least 6-12 hours to let the skin breathe.' }, { q: 'How long do HydraFacial results last?', a: 'Typically 5-7 days, longer with a consistent skincare routine.' }, { q: 'Should clients avoid exfoliation after?', a: 'Yes — avoid exfoliants for 24-48 hours.' } ] },
  { slug: 'microblading', name: 'Microblading', keywords: ['microblading aftercare instructions', 'microblading aftercare generator', 'microblading post care'], seoIntro: 'Create branded microblading aftercare sheets — healing timeline, cleaning, and what to avoid for best retention.', faq: [ { q: 'How long does microblading take to heal?', a: 'Surface healing takes about 7-14 days; full healing up to 4-6 weeks.' }, { q: 'Can clients get brows wet after microblading?', a: 'Avoid soaking and heavy moisture for the first 7-10 days.' }, { q: 'Why do brows look darker at first?', a: 'Pigment appears darker before it softens during healing.' } ] },
  { slug: 'lip-blush', name: 'Lip Blush', keywords: ['lip blush aftercare instructions', 'lip blush aftercare generator', 'lip blush tattoo post care'], seoIntro: 'Generate lip blush tattoo aftercare instructions for clients — healing, hydration, and color settling guidance.', faq: [ { q: 'How long does lip blush take to heal?', a: 'Initial healing is about 7-10 days; color settles over 4-6 weeks.' }, { q: 'Should clients keep lips moisturized?', a: 'Yes — apply the recommended balm to prevent cracking.' }, { q: 'Is peeling normal after lip blush?', a: 'Yes — light flaking during the first week is expected.' } ] },
  { slug: 'dermal-fillers', name: 'Dermal Fillers', keywords: ['dermal filler aftercare instructions', 'dermal filler aftercare generator', 'cheek filler post care'], seoIntro: 'Create dermal filler aftercare instructions with your branding — swelling, bruising, and activity guidance.', faq: [ { q: 'Is bruising normal after dermal fillers?', a: 'Mild bruising and swelling can occur and usually resolve within a week.' }, { q: 'What should clients avoid after fillers?', a: 'Strenuous exercise, alcohol, and heat for 24-48 hours.' }, { q: 'When do dermal filler results settle?', a: 'Final results typically settle within two weeks.' } ] },
  { slug: 'prp-microneedling', name: 'PRP Microneedling', keywords: ['prp microneedling aftercare instructions', 'prp facial aftercare generator', 'vampire facial post care'], seoIntro: 'Generate PRP microneedling (vampire facial) aftercare instructions branded for your clinic — redness and recovery guidance.', faq: [ { q: 'How long is downtime after PRP microneedling?', a: 'Redness and sensitivity typically last 24-72 hours.' }, { q: 'When can clients wash their face?', a: 'Usually after 24 hours with a gentle cleanser.' }, { q: 'Is sun protection needed after PRP?', a: 'Yes — strict SPF is recommended during recovery.' } ] },
  { slug: 'coolsculpting', name: 'CoolSculpting', keywords: ['coolsculpting aftercare instructions', 'coolsculpting aftercare generator', 'fat freezing post care'], seoIntro: 'Create CoolSculpting (fat freezing) aftercare instructions for clients — massage, soreness, and results timeline.', faq: [ { q: 'Is soreness normal after CoolSculpting?', a: 'Yes — tenderness, numbness, and swelling are common for days to weeks.' }, { q: 'Should clients massage the treated area?', a: 'A short massage after treatment can help, per your protocol.' }, { q: 'When are CoolSculpting results visible?', a: 'Results develop over 1-3 months as the body clears fat cells.' } ] },
  { slug: 'tca-peel', name: 'TCA Peel', keywords: ['tca peel aftercare instructions', 'tca peel aftercare generator', 'tca peel post care'], seoIntro: 'Generate TCA peel aftercare instructions branded for your clinic — peeling, hydration, and sun protection.', faq: [ { q: 'How deep is a TCA peel?', a: 'TCA peels are medium-depth and require careful aftercare and sun avoidance.' }, { q: 'How long does TCA peeling last?', a: 'Peeling generally lasts 5-7 days.' }, { q: 'Can clients use makeup during peeling?', a: 'Avoid makeup until peeling completes to prevent irritation.' } ] },
]

export function getProcedure(slug: string): Procedure | undefined {
  return PROCEDURES.find((p) => p.slug === slug)
}

export const PROCEDURE_SLUGS = PROCEDURES.map((p) => p.slug)
