import Link from 'next/link'
import { FileDown, Sparkles, Clock, CheckCircle } from 'lucide-react'
import { PROCEDURES } from '@/lib/tools/aftercare/procedures'
import { Card, CardContent } from '@/components/ui/card'

const benefits = [
  {
    icon: Sparkles,
    title: 'AI-powered content',
    description: 'Clinically accurate aftercare generated by AI, tailored to each procedure.',
  },
  {
    icon: FileDown,
    title: 'Branded PDF download',
    description: 'Your clinic name and colors on every sheet. Professional at first glance.',
  },
  {
    icon: Clock,
    title: 'Ready in seconds',
    description: 'No more copy-pasting templates. Generate, download, hand to your patient.',
  },
]

const steps = [
  { number: '01', title: 'Choose a procedure', description: 'Select from 13+ aesthetic treatments.' },
  { number: '02', title: 'Enter your clinic name', description: 'We personalise every sheet with your brand.' },
  { number: '03', title: 'Download your PDF', description: 'Print or share digitally with your patient.' },
]

export default function Home() {
  return (
    <div>
      {/* Hero */}
      <section className="mx-auto max-w-5xl px-6 pt-20 pb-16 text-center animate-rise">
        <span className="inline-block mb-4 text-xs font-semibold uppercase tracking-widest text-[var(--primary)] bg-[var(--secondary)] px-4 py-1.5 rounded-full">
          For aesthetic clinics
        </span>
        <h1 className="font-serif text-5xl sm:text-6xl font-semibold text-[var(--foreground)] leading-tight mt-2">
          Branded aftercare sheets<br className="hidden sm:block" />
          <span className="text-[var(--primary)] italic"> your patients will keep</span>
        </h1>
        <p className="mt-6 text-lg text-[var(--muted-foreground)] max-w-2xl mx-auto leading-relaxed">
          Generate professional post-procedure aftercare instructions in seconds.
          Personalised with your clinic name, downloadable as a polished PDF.
        </p>
        <div className="mt-10 flex flex-col sm:flex-row gap-3 justify-center">
          <Link
            href="/aftercare/botox"
            className="inline-flex items-center justify-center h-12 px-8 rounded-xl bg-[var(--primary)] text-white font-medium hover:opacity-90 active:scale-[0.98] transition-all"
          >
            Generate your first sheet free
          </Link>
          <Link
            href="#procedures"
            className="inline-flex items-center justify-center h-12 px-8 rounded-xl border border-[var(--border)] text-[var(--foreground)] font-medium hover:bg-[var(--secondary)] transition-colors"
          >
            See all procedures
          </Link>
        </div>
        {/* Social proof strip */}
        <p className="mt-8 text-sm text-[var(--muted-foreground)] flex items-center justify-center gap-2">
          <CheckCircle className="w-4 h-4 text-[var(--success)]" />
          No credit card required · Free plan available
        </p>
      </section>

      {/* Benefits */}
      <section className="bg-[var(--secondary)] py-16">
        <div className="mx-auto max-w-5xl px-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            {benefits.map((b, i) => (
              <div key={b.title} className={`text-center animate-rise-delay-${i + 1}`}>
                <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-[var(--primary)]/10 text-[var(--primary)] mb-4">
                  <b.icon className="w-6 h-6" />
                </div>
                <h3 className="font-serif text-lg font-semibold text-[var(--foreground)]">{b.title}</h3>
                <p className="mt-1.5 text-sm text-[var(--muted-foreground)] leading-relaxed">{b.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Procedures grid */}
      <section id="procedures" className="mx-auto max-w-5xl px-6 py-20">
        <div className="text-center mb-12">
          <h2 className="font-serif text-3xl font-semibold text-[var(--foreground)]">Choose a procedure</h2>
          <p className="mt-3 text-[var(--muted-foreground)]">13 aesthetic treatments covered. More coming soon.</p>
        </div>
        <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {PROCEDURES.map((p) => (
            <li key={p.slug}>
              <Link href={`/aftercare/${p.slug}`}>
                <Card className="card-hover h-full cursor-pointer">
                  <CardContent className="pt-6">
                    <p className="font-medium text-[var(--foreground)]">{p.name}</p>
                    <p className="mt-1 text-sm text-[var(--muted-foreground)] line-clamp-2">{p.seoIntro}</p>
                    <span className="mt-3 inline-flex items-center text-xs font-medium text-[var(--primary)]">
                      Generate aftercare →
                    </span>
                  </CardContent>
                </Card>
              </Link>
            </li>
          ))}
        </ul>
      </section>

      {/* How it works */}
      <section className="bg-[var(--muted)] py-20">
        <div className="mx-auto max-w-5xl px-6">
          <div className="text-center mb-12">
            <h2 className="font-serif text-3xl font-semibold text-[var(--foreground)]">How it works</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">
            {steps.map((s) => (
              <div key={s.number} className="text-center">
                <p className="font-serif text-5xl font-light text-[var(--primary)]/30">{s.number}</p>
                <h3 className="mt-3 font-serif text-lg font-semibold text-[var(--foreground)]">{s.title}</h3>
                <p className="mt-1.5 text-sm text-[var(--muted-foreground)]">{s.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA final */}
      <section className="mx-auto max-w-5xl px-6 py-20 text-center">
        <h2 className="font-serif text-3xl font-semibold text-[var(--foreground)]">
          Start for free today
        </h2>
        <p className="mt-3 text-[var(--muted-foreground)] max-w-xl mx-auto">
          3 free sheets per day. Upgrade to Pro for unlimited, branded PDFs and saved templates.
        </p>
        <Link
          href="/aftercare/botox"
          className="mt-8 inline-flex items-center justify-center h-12 px-10 rounded-xl bg-[var(--primary)] text-white font-medium hover:opacity-90 active:scale-[0.98] transition-all"
        >
          Generate your first sheet
        </Link>
      </section>
    </div>
  )
}
