import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions for using AftercareGen by Nimblabs.',
  alternates: {
    canonical: 'https://aftercare.nimblabs.com/terms',
  },
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 animate-rise">
      <h1 className="font-serif text-4xl font-semibold text-[var(--foreground)] mb-2">Terms of Service</h1>
      <p className="text-sm text-[var(--muted-foreground)] mb-10">Last updated: June 6, 2026</p>

      <div className="prose prose-neutral max-w-none space-y-8 text-[var(--foreground)]">

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">1. Acceptance</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            By accessing or using AftercareGen (&quot;the Service&quot;), operated by Nimblabs at
            aftercare.nimblabs.com, you agree to be bound by these Terms of Service. If you do not agree,
            do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">2. Description of service</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            AftercareGen is a software tool that allows aesthetic clinic professionals to generate
            AI-assisted, branded post-procedure aftercare instruction sheets in PDF format. The Service is
            intended for use by licensed healthcare and aesthetic professionals only.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">3. Not medical advice</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            Content generated by the Service is intended as a starting point for professional aftercare
            documentation and is <strong className="text-[var(--foreground)]">not a substitute for medical
            advice</strong>. Clinicians are solely responsible for reviewing, adapting, and approving all
            generated content before distributing it to patients. Nimblabs accepts no liability for clinical
            decisions made based on generated content.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">4. Accounts and access</h2>
          <ul className="list-disc pl-5 space-y-2 text-[var(--muted-foreground)] leading-relaxed">
            <li>You must provide accurate information when creating an account.</li>
            <li>You are responsible for maintaining the security of your account credentials.</li>
            <li>Free plan users may generate up to 3 aftercare sheets per day.</li>
            <li>Pro plan subscribers receive unlimited generation and additional features.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">5. Payments and subscriptions</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            Pro subscriptions are billed monthly or annually via Stripe. You may cancel at any time; access
            continues until the end of the current billing period. Refunds are handled case by case — contact
            us within 7 days of a charge if you believe an error occurred.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">6. Acceptable use</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">You agree not to:</p>
          <ul className="list-disc pl-5 space-y-2 text-[var(--muted-foreground)] leading-relaxed">
            <li>Use the Service for any unlawful purpose.</li>
            <li>Distribute generated content without appropriate clinical review.</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the Service&apos;s APIs.</li>
            <li>Resell or sublicense access to the Service without written permission.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">7. Intellectual property</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            The AftercareGen platform, its design, and underlying code are owned by Nimblabs. Generated PDF
            content is yours to use for your clinical practice. You retain no rights to the platform itself.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">8. Limitation of liability</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            To the maximum extent permitted by law, Nimblabs is not liable for any indirect, incidental, or
            consequential damages arising from your use of the Service. Our total liability to you for any
            claim shall not exceed the amount you paid us in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">9. Termination</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            We reserve the right to suspend or terminate accounts that violate these terms or that we believe
            pose a risk to the Service or other users, with or without prior notice.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">10. Changes to these terms</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            We may update these terms from time to time. Continued use of the Service after changes are
            posted constitutes acceptance. The date at the top of this page reflects the most recent revision.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-2xl font-semibold mb-3">11. Contact</h2>
          <p className="text-[var(--muted-foreground)] leading-relaxed">
            Questions about these terms? Email us at{' '}
            <a
              href="mailto:legal@nimblabs.com"
              className="text-[var(--primary)] hover:underline"
            >
              legal@nimblabs.com
            </a>
            .
          </p>
        </section>

      </div>
    </div>
  )
}
